// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gqlmodel

import (
	"time"
)

type Node interface {
	IsNode()
}

type Article struct {
	ID             string    `json:"id"`
	Title          string    `json:"title"`
	Body           string    `json:"body"`
	Description    string    `json:"description"`
	PublishStatus  int       `json:"publishStatus"`
	ThumbnailImage string    `json:"thumbnailImage"`
	PostedAt       time.Time `json:"postedAt"`
	CreatedAt      time.Time `json:"createdAt"`
	UpdatedAt      time.Time `json:"updatedAt"`
}

func (Article) IsNode() {}
